services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - /share/vm/docker/grafana/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /share/vm/docker/grafana/prometheus_data:/prometheus
    restart: always
    privileged: true
    environment:
      TZ: Asia/Bangkok
    network_mode: host

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    privileged: true
    environment:
      TZ: Asia/Bangkok
    command:
      - "--path.rootfs=/host"
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    volumes:
      - /share/vm/docker/grafana/grafana_data:/var/lib/grafana
    shm_size: 256mb
    privileged: true
    environment:
      TZ: Asia/Bangkok
      GF_FEATURE_TOGGLES_ENABLE: publicDashboards
    network_mode: host
    restart: unless-stopped
